"use client";

import React, { Suspense, useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, Loader2, AlertCircle, Award, Download } from "lucide-react";

import { getCampaigns, type Campaign } from "@/app/api/campaign";
import type { Donor } from "@/app/api/donor";
import type { Donation } from "@/app/api/donation";
import {
  getCertificateByDonor,
  generateCertificateForDonor,
  generatePdf,
  type Certificate,
} from "@/app/api/certificate";

import DonorForm from "@/components/website/donations/DonorForm";
import PaymentStep from "@/components/website/donations/PaymentStep";
import DonationResult from "@/components/website/donations/DonationResult";
import { getImageUrl } from "@/lib/image";

type Step = "donor" | "payment" | "success" | "failed";

function DonateFlow() {
  const searchParams = useSearchParams();
  const campaignSlug = searchParams.get("campaign") || "";
  const amountParam = Number(searchParams.get("amount") || 0);

  const [campaign, setCampaign] = useState<Campaign | null>(null);
  const [loadingCampaign, setLoadingCampaign] = useState(true);
  const [campaignError, setCampaignError] = useState<string | null>(null);

  const [step, setStep] = useState<Step>("donor");
  const [donor, setDonor] = useState<Donor | null>(null);
  const [donation, setDonation] = useState<Donation | null>(null);

  // ── Certificate polling on successful payment ────────────────────────
  // The backend generates the certificate synchronously inside createDonation,
  // so it should already exist by the time we land here. We poll briefly
  // as a safety net for any timing edge case.
  const [certificate, setCertificate] = useState<Certificate | null>(null);
  const [certLoading, setCertLoading] = useState(false);

  useEffect(() => {
    if (step !== "success" || !donor?._id) return;

    let cancelled = false;

    const loadCertificate = async () => {
      setCertLoading(true);
      try {
        // Try fetching existing certificate generated by backend
        let cert = await getCertificateByDonor(donor._id);
        // Fallback: trigger explicit certificate generation if not created yet
        if (!cert) {
          cert = await generateCertificateForDonor(donor._id);
        }
        // Ensure PDF is generated for download
        if (cert && !cert.pdfUrl) {
          cert = await generatePdf(cert._id);
        }
        if (!cancelled) setCertificate(cert);
      } catch (err) {
        console.error("Error generating/fetching certificate:", err);
      } finally {
        if (!cancelled) setCertLoading(false);
      }
    };

    loadCertificate();
    return () => {
      cancelled = true;
    };
  }, [step, donor?._id]);
  // ────────────────────────────────────────────────────────────────────

  useEffect(() => {
    if (!campaignSlug) {
      setCampaignError("No campaign was selected.");
      setLoadingCampaign(false);
      return;
    }
    let cancelled = false;
    (async () => {
      try {
        setLoadingCampaign(true);
        setCampaignError(null);
        const all = await getCampaigns();
        const match = all.find((c) => c.slug === campaignSlug);
        if (!cancelled) {
          if (!match) setCampaignError("This campaign could not be found.");
          else setCampaign(match);
        }
      } catch (err) {
        if (!cancelled) setCampaignError("Could not load this campaign.");
      } finally {
        if (!cancelled) setLoadingCampaign(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [campaignSlug]);

  if (loadingCampaign) {
    return (
      <div className="min-h-[60vh] flex flex-col items-center justify-center gap-3 text-gray-400">
        <Loader2 className="animate-spin" size={28} />
        <p className="text-sm">Loading campaign…</p>
      </div>
    );
  }

  if (campaignError || !campaign) {
    return (
      <div className="min-h-[60vh] flex flex-col items-center justify-center gap-3 text-center px-4">
        <AlertCircle className="text-[#E8542A]" size={32} />
        <p className="text-[#0f2347] font-semibold">
          {campaignError || "Campaign not found."}
        </p>
        <Link
          href="/campaigns"
          className="text-sm font-semibold text-[#1a3a6b] hover:underline"
        >
          Back to campaigns
        </Link>
      </div>
    );
  }

  const firstImage =
    typeof campaign.images?.[0] === "string" ? campaign.images[0] : undefined;
  const resolvedFirstImage = firstImage ? getImageUrl(firstImage) : undefined;

  return (
    <div className="min-h-screen bg-[#f9fafb]">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
        {step === "donor" && (
          <Link
            href={`/campaigns/${campaign.slug}`}
            className="inline-flex items-center gap-2 text-sm text-gray-500 hover:text-[#1a3a6b] mb-6 transition-colors group"
          >
            <ArrowLeft
              size={15}
              className="group-hover:-translate-x-0.5 transition-transform"
            />
            Back to campaign
          </Link>
        )}

        <div className="flex items-center gap-4 bg-white rounded-2xl border border-gray-100 p-4 mb-6 shadow-sm">
        {resolvedFirstImage && (
            <img
              src={resolvedFirstImage}
              alt={campaign.name}
              className="w-16 h-16 rounded-xl object-cover bg-gray-100 flex-shrink-0"
            />
          )}
          <div className="min-w-0">
            <p className="text-xs text-gray-400 font-semibold uppercase tracking-wide">
              Donating to
            </p>
            <p className="text-sm font-bold text-[#0f2347] truncate">
              {campaign.name}
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2 mb-6 px-1">
          {(["donor", "payment", "result"] as const).map((s, i) => {
            const active =
              (s === "donor" && step === "donor") ||
              (s === "payment" && step === "payment") ||
              (s === "result" && (step === "success" || step === "failed"));
            const done =
              (s === "donor" && step !== "donor") ||
              (s === "payment" && (step === "success" || step === "failed"));
            return (
              <React.Fragment key={s}>
                {i > 0 && (
                  <div
                    className={`h-px flex-1 ${
                      done ? "bg-[#E8542A]" : "bg-gray-200"
                    }`}
                  />
                )}
                <div
                  className={`w-6 h-6 rounded-full flex items-center justify-center text-[10px] font-bold flex-shrink-0 ${
                    active || done
                      ? "bg-[#E8542A] text-white"
                      : "bg-gray-100 text-gray-400"
                  }`}
                >
                  {i + 1}
                </div>
              </React.Fragment>
            );
          })}
        </div>

        {step === "donor" && (
          <DonorForm
            campaignId={campaign._id}
            onCreated={(createdDonor) => {
              setDonor(createdDonor);
              setStep("payment");
            }}
          />
        )}

        {step === "payment" && donor && (
          <PaymentStep
            donor={donor}
            campaignId={campaign._id}
            amount={amountParam}
            onResult={(createdDonation) => {
              setDonation(createdDonation);
              setStep(
                createdDonation.paymentStatus === "SUCCESS"
                  ? "success"
                  : "failed"
              );
            }}
          />
        )}

        {(step === "success" || step === "failed") && donor && (
          <>
            <DonationResult
              status={step}
              donor={donor}
              donation={donation}
              campaign={campaign}
              onRetry={() => setStep("payment")}
            />

            {/* Certificate block — only on success */}
            {step === "success" && (
              <div className="mt-4 bg-white rounded-2xl border border-gray-100 p-6 shadow-sm">
                {certLoading && (
                  <div className="flex items-center gap-3 text-gray-500 text-sm">
                    <Loader2 size={16} className="animate-spin" />
                    Fetching your certificate…
                  </div>
                )}

                {!certLoading && !certificate && (
                  <p className="text-xs text-gray-400">Certificate is being prepared…</p>
                )}

                {certificate && (
                  <div className="flex items-center justify-between gap-4">
                    <div className="flex items-center gap-3">
                      <div className="w-10 h-10 rounded-xl bg-[#0f2347]/10 flex items-center justify-center">
                        <Award size={18} className="text-[#0f2347]" />
                      </div>
                      <div>
                        <p className="text-sm font-bold text-[#0f2347]">
                          Your certificate is ready
                        </p>
                        <p className="text-xs text-gray-400">
                          {certificate.certificateNo}
                        </p>
                      </div>
                    </div>
                    {certificate.pdfUrl && (
                       <a
                        href={getImageUrl(certificate.pdfUrl)}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="flex items-center gap-2 bg-[#0f2347] hover:bg-[#0f2347]/90 text-white text-xs font-bold px-4 py-2.5 rounded-xl transition-colors"
                      >
                        <Download size={14} />
                        Download
                      </a>
                    )}
                  </div>
                )}
              </div>
            )}
          </>
        )}
      </div>
    </div>
  );
}

export default function DonationsPage() {
  return (
    <Suspense
      fallback={
        <div className="min-h-[60vh] flex items-center justify-center text-gray-400 text-sm">
          Loading…
        </div>
      }
    >
      <DonateFlow />
    </Suspense>
  );
}