import { CmsItem } from "@/types/cms";

export const DUMMY_BLOGS: CmsItem[] = [
  {
    id: "blog-1",
    type: "blog",
    title: "How Your Donation Feeds 100 Families This Winter",
    slug: "donation-feeds-100-families-winter",
    status: "published",
    category: "Humanitarian",
    publishedAt: "12 Jun 2025",
    featuredImage: "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=600&q=80",
    excerpt: "This winter, our ground teams reached over 100 families across remote tribal belts. Here's how every rupee you donated translated into warm meals and hope.",
    content: "<h2>Reaching Remote Communities</h2><p>Winter in the northern tribal belts brings extreme temperatures. Thanks to our generous supporters, our relief teams delivered food kits, blankets, and essential medical supplies to 105 families across 4 rural districts.</p><h2>Impact Breakdown</h2><p>Each family kit contains wheat flour, pulses, cooking oil, blankets, and hygiene essentials calculated to sustain a family of five for 45 days.</p>",
    metaTitle: "How Your Donation Feeds 100 Families | SEVA Foundation",
    metaDescription: "Read how SEVA Foundation's winter relief campaign delivered food and essential aid to 100+ families across remote regions.",
    faqs: [
      {
        question: "How are beneficiary families selected?",
        answer: "Our local survey teams assess household income, vulnerability, and geographic isolation in coordination with local village councils.",
      },
    ],
    authorName: "SEVA Relief Team",
    readTime: "4 min read",
  },
  {
    id: "blog-2",
    type: "blog",
    title: "Building Schools in Rural Rajasthan: A Year in Review",
    slug: "building-schools-rural-rajasthan-review",
    status: "published",
    category: "Education",
    publishedAt: "3 May 2025",
    featuredImage: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=600&q=80",
    excerpt: "We broke ground on four new classrooms and enrolled 240 children who had never stepped inside a school. This is their story.",
    content: "<h2>Transforming Rural Education</h2><p>Education is the bedrock of lasting empowerment. Over the past 12 months, SEVA Foundation established 4 sustainable learning centers in villages where the nearest primary school was over 8 kilometers away.</p>",
    metaTitle: "Building Schools in Rural Rajasthan | SEVA Foundation",
    metaDescription: "Annual review of SEVA Foundation's rural education program in Rajasthan, reaching 240 first-generation learners.",
    authorName: "Priya Sharma",
    readTime: "5 min read",
  },
  {
    id: "blog-3",
    type: "blog",
    title: "Free Medical Camps: What We Learned from 5,000 Patients",
    slug: "free-medical-camps-5000-patients",
    status: "draft",
    category: "Healthcare",
    publishedAt: "—",
    featuredImage: "https://images.unsplash.com/photo-1584820927498-cfe5211fd8bf?w=600&q=80",
    excerpt: "Running free camps across six districts taught us what urban medicine misses entirely. Here are the five lessons that changed how we work.",
    content: "<h2>Preventive Healthcare Gaps</h2><p>During our 2025 healthcare drive, volunteer doctors examined over 5,000 patients across 12 villages. Early detection of diabetes and hypertension accounted for 64% of life-saving interventions.</p>",
    metaTitle: "Lessons from 5,000 Medical Camp Patients | SEVA",
    metaDescription: "Insights and preventive healthcare learnings from SEVA Foundation's multi-district rural medical initiative.",
    authorName: "Dr. Rajesh Kumar",
    readTime: "6 min read",
  },
];

export const DUMMY_NEWS: CmsItem[] = [
  {
    id: "news-1",
    type: "news",
    title: "SEVA Foundation Honored with National Social Impact Award 2025",
    slug: "seva-foundation-national-social-impact-award-2025",
    status: "published",
    category: "Press Release",
    publishedAt: "28 Jul 2025",
    featuredImage: "https://images.unsplash.com/photo-1531545514256-b1400bc00f31?w=600&q=80",
    excerpt: "SEVA Foundation received the prestigious National Social Impact Award for outstanding grassroots intervention during natural disaster relief.",
    content: "<h2>Recognition of Grassroots Commitment</h2><p>In a ceremony held in New Delhi, SEVA Foundation was awarded the National Social Impact Award 2025. The honor recognizes our rapid response teams and transparent donor reporting frameworks.</p>",
    metaTitle: "National Social Impact Award 2025 | SEVA News",
    metaDescription: "SEVA Foundation wins the National Social Impact Award 2025 for exceptional grassroots relief work and transparent governance.",
    newsSource: "Times NGO Digest",
    authorName: "Media Cell",
    readTime: "3 min read",
  },
  {
    id: "news-2",
    type: "news",
    title: "MoU Signed with Global Health Initiative for Clean Water Projects",
    slug: "mou-signed-global-health-initiative-clean-water",
    status: "published",
    category: "Partnership",
    publishedAt: "14 Jun 2025",
    featuredImage: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=600&q=80",
    excerpt: "A landmark partnership to install solar-powered water filtration units in 50 drought-affected villages by the end of Q4.",
    content: "<h2>Bringing Safe Drinking Water to 50 Villages</h2><p>SEVA Foundation today formalized a strategic partnership with Global Health Initiative to deploy community filtration systems. The initiative will ensure clean drinking water for over 35,000 villagers.</p>",
    metaTitle: "Clean Water MoU Signed | SEVA Foundation News",
    metaDescription: "SEVA Foundation partners with Global Health Initiative to bring solar water filtration to 50 drought-prone villages.",
    newsSource: "Press Trust Bulletin",
    authorName: "Corporate Relations",
    readTime: "2 min read",
  },
  {
    id: "news-3",
    type: "news",
    title: "Annual Financial Transparency & Audit Report Released for FY 2024-25",
    slug: "annual-financial-transparency-audit-report-2024-25",
    status: "scheduled",
    scheduledAt: "2026-10-01T10:00",
    category: "Governance",
    publishedAt: "Scheduled",
    featuredImage: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=600&q=80",
    excerpt: "Our 100% audited financial statements are now available for public review, highlighting 91.4% direct program utilization.",
    content: "<h2>Commitment to 100% Financial Accountability</h2><p>We are proud to release our audited financial disclosures for the fiscal year 2024-25, certified by leading independent auditors.</p>",
    metaTitle: "FY 2024-25 Transparency Report | SEVA News",
    metaDescription: "Read SEVA Foundation's FY 2024-25 audited financial report demonstrating 91.4% direct program funding utilization.",
    newsSource: "SEVA Official Press",
    authorName: "Finance & Governance Unit",
    readTime: "4 min read",
  },
];

export const DUMMY_EVENTS: CmsItem[] = [
  {
    id: "event-1",
    type: "event",
    title: "Annual SEVA Charity Gala & Donor Recognition Night 2025",
    slug: "annual-seva-charity-gala-2025",
    status: "published",
    category: "Fundraiser",
    publishedAt: "15 Aug 2025",
    featuredImage: "https://images.unsplash.com/photo-1511578314322-379afb476865?w=600&q=80",
    excerpt: "Join community leaders, philanthropists, and partner organizations for an inspirational evening celebrating grassroots changemakers.",
    content: "<h2>An Evening of Purpose & Gratitude</h2><p>The Annual SEVA Charity Gala brings together patrons and changemakers to reflect on impact milestones and raise vital funding for our 2026 rural education & health initiatives.</p>",
    metaTitle: "Annual SEVA Charity Gala 2025 | Events",
    metaDescription: "Register for the SEVA Foundation Annual Charity Gala 2025. Celebrate community impact and support future initiatives.",
    eventDate: "2025-11-20T18:30",
    eventLocation: "Grand Palace Ballroom, New Delhi",
    eventOrganizer: "SEVA Event Committee",
    authorName: "Events Team",
    readTime: "3 min read",
  },
  {
    id: "event-2",
    type: "event",
    title: "Mega Youth Health & Eye Care Drive 2025",
    slug: "mega-youth-health-eye-care-drive-2025",
    status: "published",
    category: "Healthcare",
    publishedAt: "10 Jul 2025",
    featuredImage: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&q=80",
    excerpt: "Free vision screenings, corrective eyeglasses distribution, and general health checkups for school students in rural clusters.",
    content: "<h2>Comprehensive Vision Screening for 2,000 Students</h2><p>Uncorrected vision defects are a major invisible barrier to children's learning. This mega drive will screen students across 15 government schools.</p>",
    metaTitle: "Mega Youth Health & Eye Care Drive | SEVA Events",
    metaDescription: "Free eye checkups and corrective glasses distribution for 2,000 rural students by SEVA Foundation.",
    eventDate: "2025-10-12T09:00",
    eventLocation: "District Sports Complex, Alwar, Rajasthan",
    eventOrganizer: "SEVA Health Division",
    authorName: "Medical Wing",
    readTime: "2 min read",
  },
  {
    id: "event-3",
    type: "event",
    title: "Clean River Plantation & Eco-Walk Drive",
    slug: "clean-river-plantation-eco-walk-drive",
    status: "draft",
    category: "Environment",
    publishedAt: "—",
    featuredImage: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=600&q=80",
    excerpt: "Community tree plantation drive along the riverbank to prevent erosion and promote local biodiversity.",
    content: "<h2>Restoring Local Ecosystems Together</h2><p>Volunteers will plant 1,500 native saplings and participate in a guided eco-awareness walk along the riverfront.</p>",
    metaTitle: "Tree Plantation & Eco-Walk Drive | SEVA Events",
    metaDescription: "Volunteer for the SEVA Riverbank Plantation Drive and help plant 1,500 native trees.",
    eventDate: "2025-12-05T07:30",
    eventLocation: "Yamuna Riverfront Park, Block C",
    eventOrganizer: "SEVA Eco Club",
    authorName: "Green Initiative",
    readTime: "2 min read",
  },
];

export const CMS_SEED_MAP: Record<string, CmsItem[]> = {
  blog: DUMMY_BLOGS,
  news: DUMMY_NEWS,
  event: DUMMY_EVENTS,
};

export const CMS_CATEGORIES: Record<string, string[]> = {
  blog: ["General", "Humanitarian", "Education", "Healthcare", "Stories of Hope", "Volunteer Insights"],
  news: ["General", "Press Release", "Partnership", "Governance", "Media Coverage", "Announcements"],
  event: ["General", "Fundraiser", "Healthcare", "Environment", "Community Drive", "Workshop & Seminar"],
};
